name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        uses: php-actions/composer@v6
        with:
          php_version: '8.1'
          #ssh_key: ${{ secrets.SSH_KEY }}
          #ssh_key_pub: ${{ secrets.SSH_KEY_PUB }}
      # Generate and publish a copy of our generated SBOM to Manifest
      - name: Transmit generated SBOM to Manifest
        uses: manifest-cyber/manifest-github-action@main
        id: transmit
        with:
          apiKey: ${{ secrets.MANIFEST_API_KEY }}
          bomFilePath: "./bom.json"
          sbomVersion: ""
          sbomName: testing-php-name
          sbomOutput: cyclonedx-json
 